#!/usr/bin/env bash
# debug ngix server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
}
EOF
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo systemctl restart nginx
sudo systemctl enable nginx
echo "Nginx is now listening on port 80 of all active IPv4 IPs."

